[platformio]
default_envs = esp32cam

[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
src_dir = main
lib_extra_dirs = esp32cam
lib_deps =
    knolleary/PubSubClient @ ^2.8
build_flags =
    -I esp32cam
    -I config
    -DCORE_DEBUG_LEVEL=0
